### ISSUE TITLE
FirebaseMessaging.onMessageOpenedApp not triggering

### ISSUE THREAD

**Issue by tom-bailey-om** [drybnikov/klaviyo_flutter#21]
Hi,

Thanks so much for this plugin. We use Klaviyo already, so a godsend that this plugin exists so we can add Klaviyo push notifications to our app.

We have managed to get token storage and push notifications working. We also receive notification in the app if the app is in the foreground using:
```
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      debugPrint('Got a message whilst in the foreground!');
      debugPrint('Message data: ${message.data}');

      if (message.notification != null) {
        debugPrint('Message also contained a notification: ${message.notification}');
      }
    });
```
However, when the Android app is in the background and we click a notification link the app is correctly opening but **we are not getting the listener notification**:
` FirebaseMessaging.onMessageOpenedApp.listen(_handleMessage, onError: _handleError);`

If we do a test notification with a Firebase notification then we correctly get the listener firing. 

We have registered Klaviyo at startup:
`await GetIt.instance.get<Klaviyo>().initialize(prod ? 'prodId' : 'sandboxId');`
We have updated the AndroidManifest.xml as requested:
```
    <uses-permission android:name="android.permission.INTERNET" />
    <!-- Permissions for Klaviyo push notifications -->
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
```
and
```
        <service android:name="com.klaviyo.pushFcm.KlaviyoPushService" android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```
We have not setup a background listener like:
`FirebaseMessaging.onBackgroundMessage`
because we do not want to act on these.

Any suggestions on how to get the onMessageOpenedApp listener to fire would be gratefully received!

**Comment by drybnikov** [comment]
Hello, you can try to add `onBackgroundMessage` callback to top-level function:
```Dart
FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
...

// Top level functions marked as an entry point
// https://pub.dev/packages/flutter_local_notifications#-usage
Future firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // this initialization is necessary since push can be reviewed while app is
  // killed on android and will cause cold start
  await handleKlaviyoPush(message);
  await initializeFirebaseServices();
}
```
