### ISSUE TITLE
Klaviyo interfering with Firebase notifications on iOS

### ISSUE THREAD

**Issue by emilysmithson** [drybnikov/klaviyo_flutter#6]
hi there.
Thanks for this package. It works perfectly on android but we are having some difficulty on iOS. Our application needs to receive notifications from Klaviyo but also directly from firebase and we are finding that just having the klaviyo package installed means that notifications from firebase are not properly listened to. They arrive when the app is in the background but nothing happens in the foreground and deep linking is not working. Do you have any suggestions?

**Comment by Korpyc** [comment]
@emilysmithson Klaviyo on iOS work directly via APNS token & keep in mind it will not work for local running. I'm testing iOS integration on testflight builds. This is insane, but this is the only way now.
