### ISSUE TITLE
Notifications from klaviyo are not being received. 

### ISSUE THREAD

**Issue by abubakarflutter** [drybnikov/klaviyo_flutter#8]
Would you please check and confirm if notifications are really being received with using the following package? 
I have created a campaign in Klaviyo dashboard to send a notification to the device after a certain event is triggered. 
Klaviyo events are triggering with this Flutter package but notifications are not being received.

Moreover, when i paste the Klaviyo token (copied from the log in flutter debug) to send the notification to a certain device from the klaviyo dashboard it throws an error that the provided token is not associated with any account.

**Comment by drybnikov** [comment]
Hello [abubakarf](https://github.com/abubakarflutter), could you please double check notifications setup and integration according Apple and Google requirements.
You can also look on Klaviyo native platform integration: [Android](https://github.com/klaviyo/klaviyo-android-sdk), and [iOS](https://github.com/klaviyo/klaviyo-swift-sdk) projects.
Please also check Klaviyo API logs for your Klaviyo account at https://www.klaviyo.com/developer-tools/logs
