### ISSUE TITLE
Only klaviyo Events not Notifications

### ISSUE THREAD

**Issue by MoeezChohan1089** [drybnikov/klaviyo_flutter#9]
I am only gettign Klaviyo Events but not the Klaviyo Notifications. 
Woud you please check and confirm if the notifications are really working or not.

**Comment by drybnikov** [comment]
Hello Moeez, could you please double check notification setup and integration according Apple and Google requirements.
You can also look on Klaviyo native platform integration: [Android](https://github.com/klaviyo/klaviyo-android-sdk), and [iOS](https://github.com/klaviyo/klaviyo-swift-sdk) projects.
Please also check Klaviyo API logs for your Klaviyo account at https://www.klaviyo.com/developer-tools/logs
